// <auto-generated />
using ACMEData.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACMEData.Infrastructure.Migrations
{
    [DbContext(typeof(ACMEContext))]
    [Migration("20230807131740_OnModelCreate")]
    partial class OnModelCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ACMEData.Domain.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReleaseData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StarRating")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "Leaf rake with 48-inch wooden handle.",
                            Price = 19.949999999999999,
                            ProductCode = "GDN-0011",
                            ProductName = "Leaf Rake",
                            ReleaseData = "March 19, 2021",
                            StarRating = 3.2000000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "15 gallon capacity rolling garden cart",
                            Price = 32.990000000000002,
                            ProductCode = "GDN-0023",
                            ProductName = "Garden Cart",
                            ReleaseData = "March 18, 2021",
                            StarRating = 4.2000000000000002
                        },
                        new
                        {
                            ProductId = 5,
                            Description = "Curved claw steel hammer",
                            Price = 8.9000000000000004,
                            ProductCode = "TBX-0048",
                            ProductName = "Hammer",
                            ReleaseData = "May 21, 2021",
                            StarRating = 4.7999999999999998
                        },
                        new
                        {
                            ProductId = 8,
                            Description = "15-inch steel blade hand saw",
                            Price = 11.550000000000001,
                            ProductCode = "TBX-0022",
                            ProductName = "Saw",
                            ReleaseData = "May 15, 2021",
                            StarRating = 3.7000000000000002
                        },
                        new
                        {
                            ProductId = 10,
                            Description = "Standard two-button video game controller",
                            Price = 35.950000000000003,
                            ProductCode = "GMG-0042",
                            ProductName = "Video Game Controller",
                            ReleaseData = "October 15, 2020",
                            StarRating = 4.5999999999999996
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
